root = "../../"
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/risuwork ."
bin = "risuwork"
full_bin = "APP_ENV=dev APP_USER=air ./tmp/risuwork"
include_ext = ["go", "tpl", "tmpl"]
exclude_dir = [".git", ".github", "deploy", "deploy-public", "frontend", "nodejs", "java"]
include_dir = []
include_file = []
exclude_file = []
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
follow_symlink = true
log = "air.log"
poll = false
poll_interval = 500 # ms
delay = 0 # ms
stop_on_error = true
send_interrupt = false
kill_delay = 500 # nanosecond
rerun = false
rerun_delay = 500
args_bin = ["hello", "world"]

[log]
time = false
main_only = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true