version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: risuwork
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: go_container
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
    volumes:
      - ../../go:/home/webapp/go
      - ../../sql:/home/webapp/sql
    working_dir: /home/webapp/go
    depends_on:
      - mysql
  nginx:
    image: nginx:1.27
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
volumes:
  mysql_data:
