version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: risuwork
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  java:
    build:
      context: ../../
      dockerfile: java/Dockerfile
    container_name: java_container
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
    depends_on:
      - mysql
  nginx:
    image: nginx:1.27
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - java
volumes:
  mysql_data:
