name: deploy-node

on:
  workflow_dispatch:
    inputs:
      skip-deploy:
        type: boolean
        required: true
        description: "[デプロイをスキップ] 前回ビルドしたコンテナを再利用するため、上で選んでいるブランチは無視されます。"

env:
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  DB_CLUSTER_HOST: ${{ vars.DB_CLUSTER_HOST }}
  ALB_TG_ARN: ${{ vars.ALB_TG_ARN }}
  ALB_SG_ID: ${{ vars.ALB_SG_ID }}
  ALB_SUBNET_ID: ${{ vars.ALB_SUBNET_ID }}

jobs:
  deploy-and-bench:
    if: ${{ !inputs.skip-deploy }}
    runs-on: codebuild-self-hosted-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: kayac/ecspresso@v2
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
      - uses: aws-actions/amazon-ecr-login@v2
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: nodejs/Dockerfile
          tags: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com/application-repository:latest
          push: true
      - uses: docker/build-push-action@v5
        with:
          context: nginx
          tags: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com/nginx-repository:latest
          push: true
      - name: Deploy ECS
        working-directory: deploy
        run: |
          ecspresso deploy --config ecspresso.yml
      - name: Request enqueue bench
        run: |
          curl "${{ vars.TRIGGER_BENCH_ENDPOINT }}?team=${{ vars.TEAM_NAME }}&endpoint=${{ vars.APPLICATION_ENDPOINT }}&actor=${{ github.actor }}&commit=${{ github.sha }}"
  bench-only:
    if: ${{ inputs.skip-deploy }}
    runs-on: codebuild-self-hosted-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Request enqueue bench
        run: |
          curl "${{ vars.TRIGGER_BENCH_ENDPOINT }}?team=${{ vars.TEAM_NAME }}&endpoint=${{ vars.APPLICATION_ENDPOINT }}&actor=${{ github.actor }}"
