name: validate(sample)

on:
  pull_request:
  workflow_dispatch:

jobs:
  main:
    runs-on: codebuild-self-hosted-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4
      - name: Run webapp
        working-directory: local-docker/go-backend
        run: |
          docker compose up --quiet-pull -d mysql app
      - name: Go Build Cache for Docker
        uses: actions/cache@v4
        with:
          path: go-build-cache
          key: ${{ runner.os }}-go-build-cache-${{ hashFiles('**/go.sum') }}
      - name: inject go-build-cache into docker
        uses: reproducible-containers/buildkit-cache-dance@4b2444fec0c0fb9dbf175a96c094720a692ef810 # v2.1.4
        with:
          cache-source: go-build-cache
      - name: Run lightbench
        run: |
          sleep 20 && ./lightbench/linux_amd64/lightbench localhost:8080
