name: build-lightbench
on:
  push:
    tags:
      - v*
permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./benchmarker/go.mod
      - uses: goreleaser/goreleaser-action@v5
        with:
          workdir: ./benchmarker
          distribution: goreleaser
          args: release --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
