name: deploy-bench

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: codebuild-self-hosted-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Go Build Cache for Docker
        uses: actions/cache@v4
        with:
          path: go-build-cache
          key: ${{ runner.os }}-go-build-cache-${{ hashFiles('**/go.sum') }}
      - name: inject go-build-cache into docker
        uses: reproducible-containers/buildkit-cache-dance@4b2444fec0c0fb9dbf175a96c094720a692ef810 # v2.1.4
        with:
          cache-source: go-build-cache
      - uses: kayac/ecspresso@v2
      - uses: aws-actions/configure-aws-credentials@v4
        id: aws-credentials
        with:
          aws-region: ap-northeast-1
      - uses: aws-actions/amazon-ecr-login@v2
      - uses: docker/build-push-action@v6
        env:
          ACCOUNT_ID: ${{ steps.aws-credentials.outputs.aws-account-id }}
        with:
          context: benchmarker
          tags: ${{ env.ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com/benchmarker-repository:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Deploy ECS
        working-directory: benchmarker/deploy
        env:
          ACCOUNT_ID: ${{ steps.aws-credentials.outputs.aws-account-id }}
        run: |
          ecspresso deploy --config ecspresso.yml
