services:
  nginx:
    image: nginx:1.27
    container_name: nginx_container
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  app:
    build:
      context: ../../nodejs
      dockerfile: Dockerfile.dev
    container_name: nodejs_container
    restart: always
    environment:
      - DB_HOST=mysql
    ports:
      - 8080:8080
    volumes:
      - ../../nodejs:/home/webapp/nodejs
      - ../../sql:/home/webapp/sql
      - /home/webapp/nodejs/node_modules
    working_dir: /home/webapp/nodejs
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=risuwork
      - MYSQL_USER=isucon
      - MYSQL_PASSWORD=isucon
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
